# Generated by Django 3.0.7 on 2020-08-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        
    ]
