# Generated by Django 3.0.7 on 2020-08-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_auto_20200810_1950'),
    ]

    operations = [
        
    ]
