# Generated by Django 3.0.7 on 2020-08-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_auto_20200810_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='gamename',
            new_name='name',
        ),
    ]
